# Анализ временного ряда усреднения банковских резервов

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_excel('../data/required_reserves_table.xlsx')

In [4]:
df.head()

,Обязательные резервы кредитных организаций,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Обязательные резервы1;2;3;4;5 и средства на ко...,NaN,NaN,Количество кредитных организаций:,NaN,Справочно:,NaN,NaN,NaN
1,Период усреднения\nобязательных резервов\n(ука...,Фактические среднедневные остатки средств на к...,"Обязательные резервы, подлежащие усреднению на...",Обязательные резервы на счетах для их учета4,пользующихся правом усреднения обязательных ре...,действующих1,период усреднения обязательных резервов,число календарных дней в периоде усреднения об...,отчетный период6,период регулирования обязательных резервов7
2,2004-09-01 00:00:00,195.456667,8.7,116,492,1316,2004-09-01 00:00:00,30,01.08.2004 — 01.09.2004,03.09.2004 — 08.09.2004
3,2004-10-01 00:00:00,231.540323,9.1,117.3,503,1315,2004-10-01 00:00:00,31,01.09.2004 — 01.10.2004,05.10.2004 — 08.10.2004
4,2004-11-01 00:00:00,282.488333,11.5,118.9,521,1311,2004-11-01 00:00:00,30,01.10.2004 — 01.11.2004,03.11.2004 — 09.11.2004

In [5]:
df.describe()

,Обязательные резервы кредитных организаций,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
count,269,261.0,261.0,261.0,262,261,262,261,261,261
unique,269,260.0,260.0,223.0,175,205,262,7,261,261
top,Период усреднения\nобязательных резервов\n(ука...,1464.9,19.2,145.9,360,360,Справочно:,28,отчетный период6,период регулирования обязательных резервов7
freq,1,2.0,2.0,7.0,10,9,1,89,1,1

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 10 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Обязательные резервы кредитных организаций  269 non-null    object
 1   Unnamed: 1                                  261 non-null    object
 2   Unnamed: 2                                  261 non-null    object
 3   Unnamed: 3                                  261 non-null    object
 4   Unnamed: 4                                  262 non-null    object
 5   Unnamed: 5                                  261 non-null    object
 6   Unnamed: 6                                  262 non-null    object
 7   Unnamed: 7                                  261 non-null    object
 8   Unnamed: 8                                  261 non-null    object
 9   Unnamed: 9                                  261 non-null    str
dtypes: object(9), str(1)
memory usage: 21.3+ KB

In [9]:
df.columns = df.iloc[0]
df=df[1:]
df.reset_index(drop=True, inplace=True)
df.head()

,Период усреднения\nобязательных резервов\n(указан первый день),Фактические среднедневные остатки средств на корсчетах3,"Обязательные резервы, подлежащие усреднению на корсчетах4",Обязательные резервы на счетах для их учета4,пользующихся правом усреднения обязательных резервов1,действующих1,период усреднения обязательных резервов,число календарных дней в периоде усреднения обязательных резервов,отчетный период6,период регулирования обязательных резервов7
0,2004-09-01 00:00:00,195.456667,8.7,116,492,1316,2004-09-01 00:00:00,30,01.08.2004 — 01.09.2004,03.09.2004 — 08.09.2004
1,2004-10-01 00:00:00,231.540323,9.1,117.3,503,1315,2004-10-01 00:00:00,31,01.09.2004 — 01.10.2004,05.10.2004 — 08.10.2004
2,2004-11-01 00:00:00,282.488333,11.5,118.9,521,1311,2004-11-01 00:00:00,30,01.10.2004 — 01.11.2004,03.11.2004 — 09.11.2004
3,2004-12-01 00:00:00,368.259677,12,121.7,523,1304,2004-12-01 00:00:00,31,01.11.2004 — 01.12.2004,03.12.2004 — 08.12.2004
4,2005-01-01 00:00:00,356.675806,12.7,171.6,650,1300,2005-01-01 00:00:00,31,01.12.2004 — 01.01.2005,13.01.2005 — 18.01.2005

In [10]:
df.drop(columns=['пользующихся правом усреднения обязательных резервов1','действующих1','отчетный период6','период регулирования обязательных резервов7'])

,Период усреднения\nобязательных резервов\n(указан первый день),Фактические среднедневные остатки средств на корсчетах3,"Обязательные резервы, подлежащие усреднению на корсчетах4",Обязательные резервы на счетах для их учета4,период усреднения обязательных резервов,число календарных дней в периоде усреднения обязательных резервов
0,2004-09-01 00:00:00,195.456667,8.7,116,2004-09-01 00:00:00,30
1,2004-10-01 00:00:00,231.540323,9.1,117.3,2004-10-01 00:00:00,31
2,2004-11-01 00:00:00,282.488333,11.5,118.9,2004-11-01 00:00:00,30
3,2004-12-01 00:00:00,368.259677,12,121.7,2004-12-01 00:00:00,31
4,2005-01-01 00:00:00,356.675806,12.7,171.6,2005-01-01 00:00:00,31
...,...,...,...,...,...,...
264,4 Данные публикуются на 16-ый рабочий день мес...,NaN,NaN,NaN,NaN,NaN
265,5 С учетом результатов внеочередного регулиров...,NaN,NaN,NaN,NaN,NaN
266,6 Расчет размера резервируемых обязательств из...,NaN,NaN,NaN,NaN,NaN
267,7 Для отчетных периодов с августа 2004 г. по д...,NaN,NaN,NaN,NaN,NaN
268,"8 В скобках: количество кредитных организаций,...",NaN,NaN,NaN,NaN,NaN